apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: rng # optional: rng, hasher
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: rng # optional: rng, hasher
  minReplicas: 1
  maxReplicas: 10
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 10
    scaleDown:
      stabilizationWindowSeconds: 30
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 5
